[2020-04-16 14:57:42,707] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/user/1?", "request": {"name": "Alul", "age": 19, "sex": "male", "client_id": 1}, "response": {"id": 1, "name": "Alul", "age": 19, "sex": "male", "client_id": 1}}
[2020-04-16 14:57:45,696] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/user/2?", "request": {"name": "Alul", "age": 19, "sex": "male", "client_id": 1}, "response": {"status": "NOT_FOUND"}}
[2020-04-16 14:57:58,709] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/user?", "request": {"name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}, "response": {"id": 5, "name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}}
[2020-04-16 14:58:09,125] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/user/2?", "request": {"name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}, "response": {"status": "NOT_FOUND"}}
[2020-04-16 14:58:12,006] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/user/3?", "request": {"name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}, "response": {"status": "NOT_FOUND"}}
[2020-04-16 14:58:14,537] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/user/4?", "request": {"name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}, "response": {"status": "NOT_FOUND"}}
[2020-04-16 14:58:17,002] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/user/5?", "request": {"name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}, "response": {"id": 5, "name": "Fazlur", "age": 19, "sex": "male", "client_id": 1}}
[2020-04-16 15:24:46,226] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "PUT", "code": "200 OK", "uri": "/user/5?", "request": {"name": "Al", "age": 20, "sex": "male", "client_id": 1}, "response": {"id": 5, "name": "Al", "age": 20, "sex": "male", "client_id": 1}}
[2020-04-16 15:30:54,067] {/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /user/2 [POST]
Traceback (most recent call last):
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: post() got an unexpected keyword argument 'id'
[2020-04-16 15:30:54,068] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/user/2?", "request": {"name": "UL", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-16 15:31:03,498] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/user?", "request": {"name": "UL", "age": 20, "sex": "male", "client_id": 1}, "response": {"id": 6, "name": "UL", "age": 20, "sex": "male", "client_id": 1}}
[2020-04-16 15:34:05,626] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 400, "method": "POST", "code": "400 BAD REQUEST", "uri": "/user?", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2020-04-16 15:34:15,949] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 400, "method": "POST", "code": "400 BAD REQUEST", "uri": "/user?", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2020-04-16 15:34:21,171] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:42} WARNING - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/user?", "request": {"id": 2, "name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"id": 7, "name": "fast", "age": 20, "sex": "male", "client_id": 1}}
[2020-04-16 16:25:13,984] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list?", "request": {"name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:26:11,020] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list?", "request": {}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:27:29,269] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list?sex=male", "request": {"name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:28:22,431] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list?r=1&rp=20&sex=male&orderby=age&sort=desc", "request": {"name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:28:57,333] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list/?r=1&rp=20&sex=male&orderby=age&sort=desc", "request": {"name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:29:47,668] {/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/__init__.py:52} ERROR - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/list?sex=male", "request": {"name": "fast", "age": 20, "sex": "male", "client_id": 1}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-04-16 16:30:57,087] {/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /user/list [GET]
Traceback (most recent call last):
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta11/virtualenv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta11/fullstack5_alul/Restful_API/2-FlaskRouting_Controller_Blueprint/blueprints/user/resources.py", line 102, in get
    rows.append(marshal(row, Users.response_fields))
AttributeError: type object 'Users' has no attribute 'response_fields'
